//! Static builtin catalog data (`BUILTIN_FUNCTIONS`) and reserved names.
#![allow(clippy::missing_docs_in_private_items)]

use super::types::*;

/// Reserved words and builtin names that cannot be shadowed.
pub(crate) const RESERVED_WORDS: &[&str] = &[
    "true", "false", "null", "let", "in", "if", "then", "else", "and", "or", "not",
];

pub(crate) const BUILTIN_FUNCTIONS: &[BuiltinFunctionCatalogEntry] = &[
    // ── aggregate ────────────────────────────────────────────────────────────
    BuiltinFunctionCatalogEntry {
        name: "sum",
        category: "aggregate",
        parameters: &[Parameter {
            name: "values",
            fel_type: FelType::Array,
            description: Some("Array of numbers."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Sums all numeric elements in the array. Money values are rejected; use moneySum() for currency-safe aggregation.",
        null_handling: Some("Null elements are skipped. Arrays containing money emit FEL_SUM_REJECTS_MONEY and return null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "sum($items[*].amount)", result_json: "1500", note: None },
            Example { expression: "sum([10, null, 20])", result_json: "30", note: None },
            Example { expression: "sum([])", result_json: "0", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "count",
        category: "aggregate",
        parameters: &[Parameter {
            name: "values",
            fel_type: FelType::Array,
            description: Some("Array to count."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Returns the number of elements in the array, including nulls.",
        null_handling: Some("Null argument returns 0. Null elements ARE counted."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "count($items[*].name)", result_json: "3", note: None },
            Example { expression: "count([1, null, 3])", result_json: "3", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "countWhere",
        category: "aggregate",
        parameters: &[
            Parameter {
                name: "values",
                fel_type: FelType::Array,
                description: Some("Array to filter."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "predicate",
                fel_type: FelType::Boolean,
                description: Some("FEL expression evaluated per element with '$' rebound to the current element."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Number,
        return_description: None,
        description: "Counts array elements for which the predicate evaluates to true. The predicate receives each element via '$' (the self-reference is rebound per element). Special argument handling: the predicate is NOT pre-evaluated — it is evaluated once per element.",
        null_handling: Some("Null array returns 0. Null predicate result counts as false."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: true,
        examples: &[
            Example { expression: "countWhere($items[*].amount, $ > 100)", result_json: "2", note: None },
            Example { expression: "countWhere($scores[*], $ >= 60)", result_json: "4", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "sumWhere",
        category: "aggregate",
        parameters: &[
            Parameter {
                name: "values",
                fel_type: FelType::Array,
                description: Some("Array of numbers (or elements from which numeric matches are taken)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "predicate",
                fel_type: FelType::Boolean,
                description: Some("FEL expression evaluated per element with '$' rebound to the current element."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Number,
        return_description: None,
        description: "Sums numeric array elements for which the predicate evaluates to true. The predicate is NOT pre-evaluated — it is evaluated once per element.",
        null_handling: Some("Null array returns null. Non-numeric matches are skipped. No numeric matches returns 0."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: true,
        examples: &[
            Example { expression: "sumWhere([1, 2, 3, 4], $ > 2)", result_json: "7", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "avgWhere",
        category: "aggregate",
        parameters: &[
            Parameter {
                name: "values",
                fel_type: FelType::Array,
                description: Some("Array of numbers."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "predicate",
                fel_type: FelType::Boolean,
                description: Some("FEL expression evaluated per element with '$' rebound to the current element."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Number,
        return_description: None,
        description: "Arithmetic mean of numeric elements for which the predicate is true. Returns null when no elements match.",
        null_handling: Some("Null array returns null. No matches returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: true,
        examples: &[
            Example { expression: "avgWhere([40, 50, 60], $ >= 50)", result_json: "55", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "minWhere",
        category: "aggregate",
        parameters: &[
            Parameter {
                name: "values",
                fel_type: FelType::Array,
                description: Some("Array of comparable values."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "predicate",
                fel_type: FelType::Boolean,
                description: Some("FEL expression evaluated per element with '$' rebound to the current element."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Any,
        return_description: None,
        description: "Smallest element among those satisfying the predicate. Also applies to dates and strings.",
        null_handling: Some("Null array returns null. No matches returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: true,
        examples: &[
            Example { expression: "minWhere([3, 1, 4], $ > 0)", result_json: "1", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "maxWhere",
        category: "aggregate",
        parameters: &[
            Parameter {
                name: "values",
                fel_type: FelType::Array,
                description: Some("Array of comparable values."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "predicate",
                fel_type: FelType::Boolean,
                description: Some("FEL expression evaluated per element with '$' rebound to the current element."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Any,
        return_description: None,
        description: "Largest element among those satisfying the predicate. Also applies to dates and strings.",
        null_handling: Some("Null array returns null. No matches returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: true,
        examples: &[
            Example { expression: "maxWhere([3, 1, 4], $ < 4)", result_json: "3", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "every",
        category: "aggregate",
        parameters: &[
            Parameter {
                name: "values",
                fel_type: FelType::Array,
                description: Some("Array to test."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "predicate",
                fel_type: FelType::Boolean,
                description: Some("FEL expression evaluated per element with '$' rebound to the current element."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Boolean,
        return_description: None,
        description: "True if the array is empty or the predicate is true for every element. The predicate is NOT pre-evaluated — it is evaluated once per element.",
        null_handling: Some("Null array returns null. Null predicate result is not true (element fails every, does not satisfy some)."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: true,
        examples: &[
            Example { expression: "every([1, 2, 3], $ > 0)", result_json: "true", note: None },
            Example { expression: "every([], $ > 0)", result_json: "true", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "some",
        category: "aggregate",
        parameters: &[
            Parameter {
                name: "values",
                fel_type: FelType::Array,
                description: Some("Array to test."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "predicate",
                fel_type: FelType::Boolean,
                description: Some("FEL expression evaluated per element with '$' rebound to the current element."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Boolean,
        return_description: None,
        description: "True if at least one element satisfies the predicate. The predicate is NOT pre-evaluated — it is evaluated once per element.",
        null_handling: Some("Null array returns null. Null predicate result counts as false."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: true,
        examples: &[
            Example { expression: "some([0, 2, 4], $ > 3)", result_json: "true", note: None },
            Example { expression: "some([], $ > 0)", result_json: "false", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "avg",
        category: "aggregate",
        parameters: &[Parameter {
            name: "values",
            fel_type: FelType::Array,
            description: Some("Array of numbers."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Arithmetic mean of all finite numeric elements. Skips nulls and non-numeric values.",
        null_handling: Some("Null/non-numeric elements skipped. Empty array or all-null returns 0."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "avg([10, 20, 30])", result_json: "20", note: None },
            Example { expression: "avg([10, null, 30])", result_json: "20", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "min",
        category: "aggregate",
        parameters: &[Parameter {
            name: "values",
            fel_type: FelType::Array,
            description: Some("Array of numbers."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Returns the smallest finite numeric value in the array.",
        null_handling: Some("Null/non-numeric elements skipped. Empty array returns 0."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "min([5, 2, 8])", result_json: "2", note: None },
            Example { expression: "min($items[*].amount)", result_json: "100", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "max",
        category: "aggregate",
        parameters: &[Parameter {
            name: "values",
            fel_type: FelType::Array,
            description: Some("Array of numbers."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Returns the largest finite numeric value in the array.",
        null_handling: Some("Null/non-numeric elements skipped. Empty array returns 0."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "max([5, 2, 8])", result_json: "8", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    // ── string ───────────────────────────────────────────────────────────────
    BuiltinFunctionCatalogEntry {
        name: "length",
        category: "string",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::String,
            description: Some("String to measure."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Returns the number of characters in the string.",
        null_handling: Some("Null returns 0."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "length('hello')", result_json: "5", note: None },
            Example { expression: "length(null)", result_json: "0", note: None },
            Example { expression: "length($name)", result_json: "12", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "contains",
        category: "string",
        parameters: &[
            Parameter {
                name: "haystack",
                fel_type: FelType::String,
                description: Some("String to search in."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "needle",
                fel_type: FelType::String,
                description: Some("Substring to find."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if the haystack string contains the needle substring. Case-sensitive.",
        null_handling: Some("Null haystack treated as empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "contains('hello world', 'world')", result_json: "true", note: None },
            Example { expression: "contains($email, '@')", result_json: "true", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "startsWith",
        category: "string",
        parameters: &[
            Parameter {
                name: "value",
                fel_type: FelType::String,
                description: Some("String to test."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "prefix",
                fel_type: FelType::String,
                description: Some("Expected prefix."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if value starts with prefix. Case-sensitive.",
        null_handling: Some("Null value treated as empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "startsWith($url, 'https://')", result_json: "true", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "endsWith",
        category: "string",
        parameters: &[
            Parameter {
                name: "value",
                fel_type: FelType::String,
                description: Some("String to test."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "suffix",
                fel_type: FelType::String,
                description: Some("Expected suffix."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if value ends with suffix. Case-sensitive.",
        null_handling: Some("Null value treated as empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "endsWith($email, '.gov')", result_json: "true", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "substring",
        category: "string",
        parameters: &[
            Parameter {
                name: "value",
                fel_type: FelType::String,
                description: Some("Source string."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "start",
                fel_type: FelType::Number,
                description: Some("1-based start position."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "length",
                fel_type: FelType::Number,
                description: Some("Number of characters to extract."),
                required: false,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::String,
        return_description: None,
        description: "Extracts a substring starting at the 1-based position. If length is omitted, extracts to the end of the string.",
        null_handling: Some("Null value treated as empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "substring('abcdef', 2, 3)", result_json: "\"bcd\"", note: None },
            Example { expression: "substring('abcdef', 4)", result_json: "\"def\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "replace",
        category: "string",
        parameters: &[
            Parameter {
                name: "value",
                fel_type: FelType::String,
                description: Some("Source string."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "search",
                fel_type: FelType::String,
                description: Some("Literal substring to find (NOT regex)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "replacement",
                fel_type: FelType::String,
                description: Some("Replacement string."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::String,
        return_description: None,
        description: "Replaces ALL occurrences of the search literal with the replacement. Not regex — literal string match only.",
        null_handling: Some("Null value treated as empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "replace('hello world', 'world', 'there')", result_json: "\"hello there\"", note: None },
            Example { expression: "replace($phone, '-', '')", result_json: "\"5551234567\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "upper",
        category: "string",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::String,
            description: Some("String to convert."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::String,
        return_description: None,
        description: "Converts string to uppercase.",
        null_handling: Some("Null treated as empty string, returns empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "upper('hello')", result_json: "\"HELLO\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "lower",
        category: "string",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::String,
            description: Some("String to convert."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::String,
        return_description: None,
        description: "Converts string to lowercase.",
        null_handling: Some("Null treated as empty string, returns empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "lower('HELLO')", result_json: "\"hello\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "trim",
        category: "string",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::String,
            description: Some("String to trim."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::String,
        return_description: None,
        description: "Removes leading and trailing whitespace.",
        null_handling: Some("Null treated as empty string, returns empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "trim('  hello  ')", result_json: "\"hello\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "matches",
        category: "string",
        parameters: &[
            Parameter {
                name: "value",
                fel_type: FelType::String,
                description: Some("String to test."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "pattern",
                fel_type: FelType::String,
                description: Some("Regular expression pattern."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if the string matches the regular expression pattern. Pattern syntax follows the host language's regex engine (ECMA-262 for TypeScript, Python re for Python).",
        null_handling: Some("Null value treated as empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "matches($ein, '^[0-9]{2}-[0-9]{7}$')", result_json: "true", note: None },
            Example { expression: "matches($email, '^[^@]+@[^@]+$')", result_json: "true", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "format",
        category: "string",
        parameters: &[
            Parameter {
                name: "template",
                fel_type: FelType::String,
                description: Some("Format string with {0}, {1}, ... positional placeholders."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "args",
                fel_type: FelType::Any,
                description: Some("Values to substitute for placeholders."),
                required: true,
                variadic: true,
                allowed_values: None,
            },
        ],
        returns: FelType::String,
        return_description: None,
        description: "Positional string interpolation. Replaces {0}, {1}, etc. in the template with stringified arguments. Null arguments become empty string. Numbers strip trailing zeros. Booleans become 'true'/'false'.",
        null_handling: Some("Null template returns empty string. Null arguments substituted as empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "format('{0} of {1}', $current, $total)", result_json: "\"3 of 10\"", note: None },
            Example { expression: "format('Hello, {0}!', $name)", result_json: "\"Hello, Alice!\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    // ── numeric ──────────────────────────────────────────────────────────────
    BuiltinFunctionCatalogEntry {
        name: "round",
        category: "numeric",
        parameters: &[
            Parameter {
                name: "value",
                fel_type: FelType::Number,
                description: Some("Number to round."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "precision",
                fel_type: FelType::Number,
                description: Some("Decimal places (default 0)."),
                required: false,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Number,
        return_description: None,
        description: "Rounds to the specified number of decimal places using banker's rounding (round half to even).",
        null_handling: Some("Null treated as 0."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "round(3.456, 2)", result_json: "3.46", note: None },
            Example { expression: "round(2.5)", result_json: "2", note: Some("Banker's rounding: half rounds to even") },
            Example { expression: "round(3.5)", result_json: "4", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "floor",
        category: "numeric",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Number,
            description: Some("Number to floor."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Returns the largest integer less than or equal to the value.",
        null_handling: Some("Null treated as 0."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "floor(3.7)", result_json: "3", note: None },
            Example { expression: "floor(-2.3)", result_json: "-3", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "ceil",
        category: "numeric",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Number,
            description: Some("Number to ceil."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Returns the smallest integer greater than or equal to the value.",
        null_handling: Some("Null treated as 0."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "ceil(3.2)", result_json: "4", note: None },
            Example { expression: "ceil(-2.7)", result_json: "-2", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "abs",
        category: "numeric",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Number,
            description: Some("Number to take absolute value of."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Returns the absolute value of the number.",
        null_handling: Some("Null treated as 0."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "abs(-42)", result_json: "42", note: None },
            Example { expression: "abs(42)", result_json: "42", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "power",
        category: "numeric",
        parameters: &[
            Parameter {
                name: "base",
                fel_type: FelType::Number,
                description: Some("Base number."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "exponent",
                fel_type: FelType::Number,
                description: Some("Exponent."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Number,
        return_description: None,
        description: "Returns base raised to the power of exponent.",
        null_handling: Some("Null arguments treated as 0."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "power(2, 10)", result_json: "1024", note: None },
            Example { expression: "power(10, 2)", result_json: "100", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    // ── date ─────────────────────────────────────────────────────────────────
    BuiltinFunctionCatalogEntry {
        name: "today",
        category: "date",
        parameters: &[],
        returns: FelType::Date,
        return_description: None,
        description: "Returns the current date as an ISO 8601 date string (YYYY-MM-DD). Non-deterministic.",
        null_handling: Some("N/A — no parameters."),
        deterministic: false,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "today()", result_json: "\"2025-07-10\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "now",
        category: "date",
        parameters: &[],
        returns: FelType::DateTime,
        return_description: None,
        description: "Returns the current date and time as an ISO 8601 dateTime string. Non-deterministic.",
        null_handling: Some("N/A — no parameters."),
        deterministic: false,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "now()", result_json: "\"2025-07-10T14:30:00.000Z\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "year",
        category: "date",
        parameters: &[Parameter {
            name: "date",
            fel_type: FelType::Date,
            description: Some("ISO 8601 date or dateTime string."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Extracts the 4-digit year from a date.",
        null_handling: Some("Null returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "year(@2025-07-10)", result_json: "2025", note: None },
            Example { expression: "year($birthDate)", result_json: "1990", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "month",
        category: "date",
        parameters: &[Parameter {
            name: "date",
            fel_type: FelType::Date,
            description: Some("ISO 8601 date or dateTime string."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Extracts the month (1-12) from a date.",
        null_handling: Some("Null returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "month(@2025-07-10)", result_json: "7", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "day",
        category: "date",
        parameters: &[Parameter {
            name: "date",
            fel_type: FelType::Date,
            description: Some("ISO 8601 date or dateTime string."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Extracts the day of month (1-31) from a date.",
        null_handling: Some("Null returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "day(@2025-07-10)", result_json: "10", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "hours",
        category: "date",
        parameters: &[Parameter {
            name: "dateTime",
            fel_type: FelType::DateTime,
            description: Some("ISO 8601 dateTime or time string."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Extracts the hour component (0-23) from a dateTime or time value.",
        null_handling: Some("Null returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "hours(@2025-07-10T14:30:00Z)", result_json: "14", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "minutes",
        category: "date",
        parameters: &[Parameter {
            name: "dateTime",
            fel_type: FelType::DateTime,
            description: Some("ISO 8601 dateTime or time string."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Extracts the minute component (0-59) from a dateTime or time value.",
        null_handling: Some("Null returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "minutes(@2025-07-10T14:30:00Z)", result_json: "30", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "seconds",
        category: "date",
        parameters: &[Parameter {
            name: "dateTime",
            fel_type: FelType::DateTime,
            description: Some("ISO 8601 dateTime or time string."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Extracts the second component (0-59) from a dateTime or time value.",
        null_handling: Some("Null returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "seconds(@2025-07-10T14:30:45Z)", result_json: "45", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "time",
        category: "date",
        parameters: &[
            Parameter {
                name: "hours",
                fel_type: FelType::Number,
                description: Some("Hour (0-23)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "minutes",
                fel_type: FelType::Number,
                description: Some("Minute (0-59)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "seconds",
                fel_type: FelType::Number,
                description: Some("Second (0-59)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Time,
        return_description: None,
        description: "Constructs an HH:MM:SS time string from numeric components.",
        null_handling: Some("Null components treated as 0."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "time(14, 30, 0)", result_json: "\"14:30:00\"", note: None },
            Example { expression: "time(9, 5, 30)", result_json: "\"09:05:30\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "dateDiff",
        category: "date",
        parameters: &[
            Parameter {
                name: "date1",
                fel_type: FelType::Date,
                description: Some("First date (ISO 8601)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "date2",
                fel_type: FelType::Date,
                description: Some("Second date (ISO 8601)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "unit",
                fel_type: FelType::String,
                description: Some("Unit of measurement."),
                required: true,
                variadic: false,
                allowed_values: Some(&["days", "months", "years"]),
            },
        ],
        returns: FelType::Number,
        return_description: None,
        description: "Returns the difference laterDate − earlierDate in the specified unit (arguments: date1 as laterDate, date2 as earlierDate). Result is positive when date1 > date2, negative when date1 < date2. For months/years, incomplete periods are truncated (not rounded).",
        null_handling: Some("Null or invalid dates return null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "dateDiff(@2025-07-10, @2025-01-01, 'days')", result_json: "190", note: None },
            Example { expression: "dateDiff($endDate, $startDate, 'months')", result_json: "6", note: None },
            Example { expression: "dateDiff(today(), $birthDate, 'years')", result_json: "35", note: Some("Age calculation") },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "dateAdd",
        category: "date",
        parameters: &[
            Parameter {
                name: "date",
                fel_type: FelType::Date,
                description: Some("Base date (ISO 8601)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "amount",
                fel_type: FelType::Number,
                description: Some("Number of units to add (negative to subtract)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "unit",
                fel_type: FelType::String,
                description: Some("Unit of measurement."),
                required: true,
                variadic: false,
                allowed_values: Some(&["days", "months", "years"]),
            },
        ],
        returns: FelType::Date,
        return_description: Some("ISO 8601 date string (YYYY-MM-DD)."),
        description: "Adds the specified number of units to a date. Negative values subtract. Month/year arithmetic handles end-of-month overflow per the host language's Date implementation.",
        null_handling: Some("Null date returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "dateAdd(@2025-01-15, 30, 'days')", result_json: "\"2025-02-14\"", note: None },
            Example { expression: "dateAdd(today(), 1, 'years')", result_json: "\"2026-07-10\"", note: None },
            Example { expression: "dateAdd($startDate, -6, 'months')", result_json: "\"2025-01-10\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "timeDiff",
        category: "date",
        parameters: &[
            Parameter {
                name: "laterTime",
                fel_type: FelType::Time,
                description: Some("Later ISO 8601 time string (HH:MM:SS)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "earlierTime",
                fel_type: FelType::Time,
                description: Some("Earlier ISO 8601 time string (HH:MM:SS)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Number,
        return_description: Some("Signed difference in whole seconds: laterTime minus earlierTime (positive when the first argument is later in the day)."),
        description: "Difference in seconds between two time-of-day strings. Distinct from duration(), which parses an ISO 8601 duration and returns milliseconds.",
        null_handling: Some("Invalid time strings produce a diagnostic and null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "timeDiff('14:30:00', '13:00:00')", result_json: "5400", note: None },
            Example { expression: "timeDiff('13:00:00', '14:30:00')", result_json: "-5400", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "duration",
        category: "date",
        parameters: &[Parameter {
            name: "isoDuration",
            fel_type: FelType::String,
            description: Some("ISO 8601 duration (PnYnMnDTnHnMnS subset), optional leading minus."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Parses a duration string and returns its length in milliseconds. Years/months in the date part use fixed 365-day years and 30-day months (not calendar arithmetic). Distinct from timeDiff, which compares two clock times in seconds.",
        null_handling: Some("Null argument returns null. Invalid strings produce an error diagnostic and null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "duration('PT1H')", result_json: "3600000", note: None },
            Example { expression: "duration('P1D')", result_json: "86400000", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    // ── logical ──────────────────────────────────────────────────────────────
    BuiltinFunctionCatalogEntry {
        name: "if",
        category: "logical",
        parameters: &[
            Parameter {
                name: "condition",
                fel_type: FelType::Boolean,
                description: Some("Condition to evaluate."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "thenValue",
                fel_type: FelType::Any,
                description: Some("Value returned when condition is true."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "elseValue",
                fel_type: FelType::Any,
                description: Some("Value returned when condition is false."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Any,
        return_description: Some("Type matches whichever branch is selected."),
        description: "Conditional function. Returns thenValue when condition is true, elseValue when false. Only the selected branch is evaluated (short-circuit). Alternative syntax: 'if cond then a else b' (keyword form). Note: 'if' is a reserved word; this function is special-cased in the parser.",
        null_handling: Some("Null condition is an evaluation error."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: true,
        examples: &[
            Example { expression: "if($age >= 18, 'adult', 'minor')", result_json: "\"adult\"", note: None },
            Example { expression: "if($status = 'married', $income * 0.75, $income)", result_json: "45000", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "coalesce",
        category: "logical",
        parameters: &[Parameter {
            name: "values",
            fel_type: FelType::Any,
            description: Some("Values to check."),
            required: true,
            variadic: true,
            allowed_values: None,
        }],
        returns: FelType::Any,
        return_description: None,
        description: "Returns the first argument that is not null, undefined, or empty string. If all arguments are null/empty, returns null.",
        null_handling: Some("Core purpose is null handling — returns first non-null, non-empty value."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "coalesce($preferredName, $firstName, 'Unknown')", result_json: "\"Alice\"", note: None },
            Example { expression: "coalesce(null, '', 'fallback')", result_json: "\"fallback\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "empty",
        category: "logical",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to test."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if the value is null, undefined, empty string (''), or an empty array ([]). Broader than a simple null check.",
        null_handling: Some("Null returns true (that's the point)."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "empty(null)", result_json: "true", note: None },
            Example { expression: "empty('')", result_json: "true", note: None },
            Example { expression: "empty([])", result_json: "true", note: None },
            Example { expression: "empty('hello')", result_json: "false", note: None },
            Example { expression: "empty(0)", result_json: "false", note: Some("0 is not empty") },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "present",
        category: "logical",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to test."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Boolean,
        return_description: None,
        description: "Inverse of empty(). Returns true if the value is non-null, non-empty-string, and non-empty-array.",
        null_handling: Some("Null returns false."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "present($email)", result_json: "true", note: None },
            Example { expression: "present(null)", result_json: "false", note: None },
            Example { expression: "not empty($email) or not empty($phone)", result_json: "true", note: Some("Equivalent to: present($email) or present($phone)") },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "selected",
        category: "logical",
        parameters: &[
            Parameter {
                name: "value",
                fel_type: FelType::Any,
                description: Some("Field value (string for choice, array for multiChoice)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "option",
                fel_type: FelType::String,
                description: Some("Option value to check for."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Boolean,
        return_description: None,
        description: "For multiChoice (array): returns true if the option is included in the array. For choice (string): returns true if value equals option. Designed for testing selected options in choice/multiChoice fields.",
        null_handling: Some("Null value returns false."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "selected($categories, 'personnel')", result_json: "true", note: Some("multiChoice field") },
            Example { expression: "selected($status, 'active')", result_json: "true", note: Some("choice field") },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    // ── type ─────────────────────────────────────────────────────────────────
    BuiltinFunctionCatalogEntry {
        name: "isNumber",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to test."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if the value is a finite number (not NaN).",
        null_handling: Some("Null returns false."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "isNumber(42)", result_json: "true", note: None },
            Example { expression: "isNumber('42')", result_json: "false", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "isString",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to test."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if the value is a string.",
        null_handling: Some("Null returns false."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "isString('hello')", result_json: "true", note: None },
            Example { expression: "isString(42)", result_json: "false", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "isDate",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to test."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if the value can be parsed as a valid date.",
        null_handling: Some("Null returns false."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "isDate('2025-07-10')", result_json: "true", note: None },
            Example { expression: "isDate('not-a-date')", result_json: "false", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "isNull",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to test."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if the value is null, undefined, or empty string. Note: broader than a strict null check — empty string is also considered 'null' in FEL.",
        null_handling: Some("Null returns true (that's the point)."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "isNull(null)", result_json: "true", note: None },
            Example { expression: "isNull('')", result_json: "true", note: None },
            Example { expression: "isNull(0)", result_json: "false", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "typeOf",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to inspect."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::String,
        return_description: Some("One of: 'string', 'number', 'boolean', 'array', 'object', 'null'."),
        description: "Returns the FEL type name of the value.",
        null_handling: Some("Null returns 'null'."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "typeOf(42)", result_json: "\"number\"", note: None },
            Example { expression: "typeOf([1,2])", result_json: "\"array\"", note: None },
            Example { expression: "typeOf(null)", result_json: "\"null\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    // cast functions: category changed cast → type to match schema (schema is authoritative)
    BuiltinFunctionCatalogEntry {
        name: "number",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to coerce to number."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Explicit type cast to number. Strings are parsed as numbers. Returns null if coercion fails.",
        null_handling: Some("Null returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "number('42')", result_json: "42", note: None },
            Example { expression: "number('3.14')", result_json: "3.14", note: None },
            Example { expression: "number('abc')", result_json: "null", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "string",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to coerce to string."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::String,
        return_description: None,
        description: "Explicit type cast to string. Null becomes empty string. Numbers, booleans, and dates are stringified.",
        null_handling: Some("Null returns empty string ''."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "string(42)", result_json: "\"42\"", note: None },
            Example { expression: "string(true)", result_json: "\"true\"", note: None },
            Example { expression: "string(null)", result_json: "\"\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "boolean",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to coerce to boolean."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Boolean,
        return_description: None,
        description: "Explicit type cast to boolean. Accepts: booleans (pass-through), numbers (0 = false, non-zero = true), strings 'true'/'false'. Other values produce an evaluation error.",
        null_handling: Some("Null returns false."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "boolean(1)", result_json: "true", note: None },
            Example { expression: "boolean(0)", result_json: "false", note: None },
            Example { expression: "boolean('true')", result_json: "true", note: None },
            Example { expression: "boolean(null)", result_json: "false", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "date",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to validate/coerce as ISO 8601 date."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Date,
        return_description: None,
        description: "Validates and returns the input as an ISO 8601 date string. If the input is not a valid date, produces an evaluation error.",
        null_handling: Some("Null returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "date('2025-07-10')", result_json: "\"2025-07-10\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    // ── money ─────────────────────────────────────────────────────────────────
    BuiltinFunctionCatalogEntry {
        name: "money",
        category: "money",
        parameters: &[
            Parameter {
                name: "amount",
                fel_type: FelType::Number,
                description: Some("Monetary amount."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "currency",
                fel_type: FelType::String,
                description: Some("ISO 4217 currency code (e.g., 'USD', 'EUR')."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Money,
        return_description: Some("Object: {amount: number, currency: string}."),
        description: "Constructs a money object from an amount and currency code.",
        null_handling: Some("Null arguments produce a money object with null/undefined fields."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "money(50000, 'USD')", result_json: "{\"amount\": 50000, \"currency\": \"USD\"}", note: None },
            Example { expression: "money($total, 'EUR')", result_json: "{\"amount\": 12500, \"currency\": \"EUR\"}", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "moneyAmount",
        category: "money",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Money,
            description: Some("Money object."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Extracts the numeric amount from a money object.",
        null_handling: Some("Null or non-money value returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "moneyAmount($budget)", result_json: "50000", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "moneyCurrency",
        category: "money",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Money,
            description: Some("Money object."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::String,
        return_description: None,
        description: "Extracts the currency code from a money object.",
        null_handling: Some("Null or non-money value returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "moneyCurrency($budget)", result_json: "\"USD\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "moneyAdd",
        category: "money",
        parameters: &[
            Parameter {
                name: "a",
                fel_type: FelType::Money,
                description: Some("First money object."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "b",
                fel_type: FelType::Money,
                description: Some("Second money object. Must have the same currency as first."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Money,
        return_description: None,
        description: "Adds two money objects. Uses the currency from the first non-null operand. Per the spec, both operands SHOULD have the same currency; implementations MAY error on mismatched currencies.",
        null_handling: Some("Null operand returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "moneyAdd(money(100, 'USD'), money(250, 'USD'))", result_json: "{\"amount\": 350, \"currency\": \"USD\"}", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "moneySum",
        category: "money",
        parameters: &[Parameter {
            name: "values",
            fel_type: FelType::Array,
            description: Some("Array of money objects."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Money,
        return_description: None,
        description: "Sums an array of money objects. Returns a money object with the currency from the first element. All elements SHOULD have the same currency.",
        null_handling: Some("Null elements skipped. Empty array returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "moneySum($lineItems[*].cost)", result_json: "{\"amount\": 1500, \"currency\": \"USD\"}", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "moneySumWhere",
        category: "money",
        parameters: &[
            Parameter {
                name: "values",
                fel_type: FelType::Array,
                description: Some("Array of money objects."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "predicate",
                fel_type: FelType::Boolean,
                description: Some("FEL expression evaluated per element with '$' rebound to the current money value."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Money,
        return_description: None,
        description: "Sums money array elements for which the predicate evaluates to true. Matched elements MUST share the same currency. The predicate is NOT pre-evaluated — it is evaluated once per element.",
        null_handling: Some("Null array returns null. No matches returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: true,
        examples: &[
            Example { expression: "moneySumWhere([money(100,'USD'), money(200,'USD')], moneyAmount($) > 50)", result_json: "{\"amount\": 300, \"currency\": \"USD\"}", note: None },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    // ── locale ───────────────────────────────────────────────────────────────
    BuiltinFunctionCatalogEntry {
        name: "locale",
        category: "locale",
        parameters: &[],
        returns: FelType::String,
        return_description: None,
        description: "Returns the active BCP 47 locale tag from the evaluation context.",
        null_handling: Some("When the host has not set a locale, returns null."),
        deterministic: false,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "locale()", result_json: "\"en-US\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Formspec,
    },
    BuiltinFunctionCatalogEntry {
        name: "runtimeMeta",
        category: "locale",
        parameters: &[Parameter {
            name: "key",
            fel_type: FelType::String,
            description: Some("Key in the host-provided runtime metadata bag."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Any,
        return_description: None,
        description: "Reads a value from runtime metadata supplied by the host.",
        null_handling: Some("Missing key returns null."),
        deterministic: false,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "runtimeMeta('tenantId')", result_json: "\"acme-42\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Formspec,
    },
    BuiltinFunctionCatalogEntry {
        name: "pluralCategory",
        category: "locale",
        parameters: &[
            Parameter {
                name: "count",
                fel_type: FelType::Number,
                description: Some("Numeric count for plural rule selection."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "localeTag",
                fel_type: FelType::String,
                description: Some("Optional BCP 47 tag; defaults to locale()."),
                required: false,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::String,
        return_description: None,
        description: "Returns the CLDR cardinal plural category (zero, one, two, few, many, other) for the count and locale.",
        null_handling: Some("Null count returns null."),
        deterministic: true,
        emit_deterministic_explicitly: true,
        short_circuit: false,
        examples: &[
            Example { expression: "pluralCategory(1)", result_json: "\"one\"", note: None },
            Example { expression: "pluralCategory(2, 'en')", result_json: "\"other\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Formspec,
    },
    // ── mip ──────────────────────────────────────────────────────────────────
    BuiltinFunctionCatalogEntry {
        name: "valid",
        category: "mip",
        parameters: &[Parameter {
            name: "path",
            fel_type: FelType::String,
            description: Some("Field path (NOT evaluated as expression — extracted as literal path string)."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if the field at the given path has zero validation errors. The argument is a field reference path, not a general expression — the parser extracts it as a literal string rather than evaluating it.",
        null_handling: Some("N/A — path is a literal reference."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "valid($totalBudget)", result_json: "true", note: None },
            Example { expression: "valid($email) and valid($phone)", result_json: "false", note: None },
        ],
        since_version: "1.0",
        package: Package::Formspec,
    },
    BuiltinFunctionCatalogEntry {
        name: "relevant",
        category: "mip",
        parameters: &[Parameter {
            name: "path",
            fel_type: FelType::String,
            description: Some("Field path (literal, not evaluated)."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns the computed relevance (visibility) state of the field at the given path. True means the field is visible/active.",
        null_handling: Some("N/A — path is a literal reference."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "relevant($spouseInfo)", result_json: "false", note: None },
        ],
        since_version: "1.0",
        package: Package::Formspec,
    },
    BuiltinFunctionCatalogEntry {
        name: "readonly",
        category: "mip",
        parameters: &[Parameter {
            name: "path",
            fel_type: FelType::String,
            description: Some("Field path (literal, not evaluated)."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns the computed readonly state of the field at the given path.",
        null_handling: Some("N/A — path is a literal reference."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "readonly($approvedAmount)", result_json: "true", note: None },
        ],
        since_version: "1.0",
        package: Package::Formspec,
    },
    BuiltinFunctionCatalogEntry {
        name: "required",
        category: "mip",
        parameters: &[Parameter {
            name: "path",
            fel_type: FelType::String,
            description: Some("Field path (literal, not evaluated)."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns the computed required state of the field at the given path.",
        null_handling: Some("N/A — path is a literal reference."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "required($email)", result_json: "true", note: None },
        ],
        since_version: "1.0",
        package: Package::Formspec,
    },
    // ── repeat ───────────────────────────────────────────────────────────────
    BuiltinFunctionCatalogEntry {
        name: "prev",
        category: "repeat",
        parameters: &[Parameter {
            name: "fieldName",
            fel_type: FelType::String,
            description: Some("Name of the sibling field to read from the previous repeat instance."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Any,
        return_description: None,
        description: "Returns the value of the named field from the previous repeat instance (index - 1). Must be called within a repeat context. Returns null if at the first instance or not inside a repeat.",
        null_handling: Some("Returns null when no previous instance exists."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "prev('runningTotal')", result_json: "500", note: Some("Value from previous row") },
        ],
        since_version: "1.0",
        package: Package::Formspec,
    },
    BuiltinFunctionCatalogEntry {
        name: "next",
        category: "repeat",
        parameters: &[Parameter {
            name: "fieldName",
            fel_type: FelType::String,
            description: Some("Name of the sibling field to read from the next repeat instance."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Any,
        return_description: None,
        description: "Returns the value of the named field from the next repeat instance (index + 1). Must be called within a repeat context. Returns null if at the last instance or not inside a repeat.",
        null_handling: Some("Returns null when no next instance exists."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "next('amount')", result_json: "200", note: Some("Peek at next row's value") },
        ],
        since_version: "1.0",
        package: Package::Formspec,
    },
    BuiltinFunctionCatalogEntry {
        name: "parent",
        category: "repeat",
        parameters: &[Parameter {
            name: "fieldName",
            fel_type: FelType::String,
            description: Some("Name of the ancestor field to find."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Any,
        return_description: None,
        description: "Walks up the path hierarchy from the current item and returns the value of the first ancestor field matching the given name. Useful for accessing enclosing group data from within nested repeats.",
        null_handling: Some("Returns null if no ancestor field with that name is found."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "parent('projectName')", result_json: "\"Infrastructure Upgrade\"", note: None },
        ],
        since_version: "1.0",
        package: Package::Formspec,
    },
    // instance: category changed instance → logical to match schema (schema is authoritative).
    // Placed at the end to match canonical schema function ordering.
    BuiltinFunctionCatalogEntry {
        name: "instance",
        category: "logical",
        parameters: &[
            Parameter {
                name: "name",
                fel_type: FelType::String,
                description: Some("Name of the secondary data source (must match a key in the definition's 'instances' object)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "path",
                fel_type: FelType::String,
                description: Some("Dot-notation path within the instance data."),
                required: false,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Any,
        return_description: None,
        description: "Retrieves data from a named secondary instance. Typically invoked via the '@instance(\"name\")' context reference syntax in FEL, which the parser translates to this function call. The optional path parameter drills into the instance data.",
        null_handling: Some("Returns null/undefined if instance name not found or path doesn't exist."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example { expression: "@instance('priorYear').totalExpenditure", result_json: "200000", note: None },
            Example { expression: "@instance('agencies')", result_json: "[{\"code\": \"DOE\", \"name\": \"Dept of Energy\"}]", note: None },
        ],
        since_version: "1.0",
        package: Package::Formspec,
    },
];

/// Slice of all built-in functions (names reserved for [`ExtensionRegistry::register`]).
pub fn builtin_function_catalog() -> &'static [BuiltinFunctionCatalogEntry] {
    BUILTIN_FUNCTIONS
}

/// Catalog filtered to entries reachable from `package`.
///
/// `Package::Formspec` returns the union of `Universal` and `Formspec` entries
/// (formspec hosts can call everything). `Package::Universal` returns only
/// `Universal` entries — appropriate for hosts that use [`crate::MapEnvironment`] or
/// any non-formspec [`crate::Environment`] implementation.
pub fn builtin_function_catalog_for(
    package: Package,
) -> impl Iterator<Item = &'static BuiltinFunctionCatalogEntry> {
    BUILTIN_FUNCTIONS.iter().filter(move |e| match package {
        Package::Universal => matches!(e.package, Package::Universal),
        Package::Formspec => true, // Universal ∪ Formspec
    })
}
