//! Static builtin catalog data (`BUILTIN_FUNCTIONS`) and reserved names.
#![allow(clippy::missing_docs_in_private_items)]

use super::super::types::*;

pub(super) const ENTRIES: &[BuiltinFunctionCatalogEntry] = &[
    // ── aggregate ────────────────────────────────────────────────────────────
    BuiltinFunctionCatalogEntry {
        name: "sum",
        category: "aggregate",
        parameters: &[Parameter {
            name: "values",
            fel_type: FelType::Array,
            description: Some("Array of numbers."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Sums all numeric elements in the array. Money values are rejected; use moneySum() for currency-safe aggregation.",
        null_handling: Some(
            "Null elements are skipped. Arrays containing money emit FEL_SUM_REJECTS_MONEY and return null.",
        ),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "sum($items[*].amount)",
                result_json: "1500",
                note: None,
            },
            Example {
                expression: "sum([10, null, 20])",
                result_json: "30",
                note: None,
            },
            Example {
                expression: "sum([])",
                result_json: "0",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "count",
        category: "aggregate",
        parameters: &[Parameter {
            name: "values",
            fel_type: FelType::Array,
            description: Some("Array to count."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Returns the number of elements in the array, including nulls.",
        null_handling: Some("Null argument returns 0. Null elements ARE counted."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "count($items[*].name)",
                result_json: "3",
                note: None,
            },
            Example {
                expression: "count([1, null, 3])",
                result_json: "3",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "countWhere",
        category: "aggregate",
        parameters: &[
            Parameter {
                name: "values",
                fel_type: FelType::Array,
                description: Some("Array to filter."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "predicate",
                fel_type: FelType::Boolean,
                description: Some(
                    "FEL expression evaluated per element with '$' rebound to the current element.",
                ),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Number,
        return_description: None,
        description: "Counts array elements for which the predicate evaluates to true. The predicate receives each element via '$' (the self-reference is rebound per element). Special argument handling: the predicate is NOT pre-evaluated — it is evaluated once per element.",
        null_handling: Some("Null array returns 0. Null predicate result counts as false."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: true,
        examples: &[
            Example {
                expression: "countWhere($items[*].amount, $ > 100)",
                result_json: "2",
                note: None,
            },
            Example {
                expression: "countWhere($scores[*], $ >= 60)",
                result_json: "4",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "sumWhere",
        category: "aggregate",
        parameters: &[
            Parameter {
                name: "values",
                fel_type: FelType::Array,
                description: Some(
                    "Array of numbers (or elements from which numeric matches are taken).",
                ),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "predicate",
                fel_type: FelType::Boolean,
                description: Some(
                    "FEL expression evaluated per element with '$' rebound to the current element.",
                ),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Number,
        return_description: None,
        description: "Sums numeric array elements for which the predicate evaluates to true. The predicate is NOT pre-evaluated — it is evaluated once per element.",
        null_handling: Some(
            "Null array returns null. Non-numeric matches are skipped. No numeric matches returns 0.",
        ),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: true,
        examples: &[Example {
            expression: "sumWhere([1, 2, 3, 4], $ > 2)",
            result_json: "7",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "avgWhere",
        category: "aggregate",
        parameters: &[
            Parameter {
                name: "values",
                fel_type: FelType::Array,
                description: Some("Array of numbers."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "predicate",
                fel_type: FelType::Boolean,
                description: Some(
                    "FEL expression evaluated per element with '$' rebound to the current element.",
                ),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Number,
        return_description: None,
        description: "Arithmetic mean of numeric elements for which the predicate is true. Returns null when no elements match.",
        null_handling: Some("Null array returns null. No matches returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: true,
        examples: &[Example {
            expression: "avgWhere([40, 50, 60], $ >= 50)",
            result_json: "55",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "minWhere",
        category: "aggregate",
        parameters: &[
            Parameter {
                name: "values",
                fel_type: FelType::Array,
                description: Some("Array of comparable values."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "predicate",
                fel_type: FelType::Boolean,
                description: Some(
                    "FEL expression evaluated per element with '$' rebound to the current element.",
                ),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Any,
        return_description: None,
        description: "Smallest element among those satisfying the predicate. Also applies to dates and strings.",
        null_handling: Some("Null array returns null. No matches returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: true,
        examples: &[Example {
            expression: "minWhere([3, 1, 4], $ > 0)",
            result_json: "1",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "maxWhere",
        category: "aggregate",
        parameters: &[
            Parameter {
                name: "values",
                fel_type: FelType::Array,
                description: Some("Array of comparable values."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "predicate",
                fel_type: FelType::Boolean,
                description: Some(
                    "FEL expression evaluated per element with '$' rebound to the current element.",
                ),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Any,
        return_description: None,
        description: "Largest element among those satisfying the predicate. Also applies to dates and strings.",
        null_handling: Some("Null array returns null. No matches returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: true,
        examples: &[Example {
            expression: "maxWhere([3, 1, 4], $ < 4)",
            result_json: "3",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "every",
        category: "aggregate",
        parameters: &[
            Parameter {
                name: "values",
                fel_type: FelType::Array,
                description: Some("Array to test."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "predicate",
                fel_type: FelType::Boolean,
                description: Some(
                    "FEL expression evaluated per element with '$' rebound to the current element.",
                ),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Boolean,
        return_description: None,
        description: "True if the array is empty or the predicate is true for every element. The predicate is NOT pre-evaluated — it is evaluated once per element.",
        null_handling: Some(
            "Null array returns null. Null predicate result is not true (element fails every, does not satisfy some).",
        ),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: true,
        examples: &[
            Example {
                expression: "every([1, 2, 3], $ > 0)",
                result_json: "true",
                note: None,
            },
            Example {
                expression: "every([], $ > 0)",
                result_json: "true",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "some",
        category: "aggregate",
        parameters: &[
            Parameter {
                name: "values",
                fel_type: FelType::Array,
                description: Some("Array to test."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "predicate",
                fel_type: FelType::Boolean,
                description: Some(
                    "FEL expression evaluated per element with '$' rebound to the current element.",
                ),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Boolean,
        return_description: None,
        description: "True if at least one element satisfies the predicate. The predicate is NOT pre-evaluated — it is evaluated once per element.",
        null_handling: Some("Null array returns null. Null predicate result counts as false."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: true,
        examples: &[
            Example {
                expression: "some([0, 2, 4], $ > 3)",
                result_json: "true",
                note: None,
            },
            Example {
                expression: "some([], $ > 0)",
                result_json: "false",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "avg",
        category: "aggregate",
        parameters: &[Parameter {
            name: "values",
            fel_type: FelType::Array,
            description: Some("Array of numbers."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Arithmetic mean of all finite numeric elements. Skips nulls and non-numeric values.",
        null_handling: Some(
            "Null/non-numeric elements skipped. Empty array or all-null returns 0.",
        ),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "avg([10, 20, 30])",
                result_json: "20",
                note: None,
            },
            Example {
                expression: "avg([10, null, 30])",
                result_json: "20",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "min",
        category: "aggregate",
        parameters: &[Parameter {
            name: "values",
            fel_type: FelType::Array,
            description: Some("Array of numbers."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Returns the smallest finite numeric value in the array.",
        null_handling: Some("Null/non-numeric elements skipped. Empty array returns 0."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "min([5, 2, 8])",
                result_json: "2",
                note: None,
            },
            Example {
                expression: "min($items[*].amount)",
                result_json: "100",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "max",
        category: "aggregate",
        parameters: &[Parameter {
            name: "values",
            fel_type: FelType::Array,
            description: Some("Array of numbers."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Returns the largest finite numeric value in the array.",
        null_handling: Some("Null/non-numeric elements skipped. Empty array returns 0."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "max([5, 2, 8])",
            result_json: "8",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
];
