//! Static builtin catalog data (`BUILTIN_FUNCTIONS`) and reserved names.
#![allow(clippy::missing_docs_in_private_items)]

use super::super::types::*;

pub(super) const ENTRIES: &[BuiltinFunctionCatalogEntry] = &[
    // ── date ─────────────────────────────────────────────────────────────────
    BuiltinFunctionCatalogEntry {
        name: "today",
        category: "date",
        parameters: &[],
        returns: FelType::Date,
        return_description: None,
        description: "Returns the current date as an ISO 8601 date string (YYYY-MM-DD). Non-deterministic.",
        null_handling: Some("N/A — no parameters."),
        deterministic: false,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "today()",
            result_json: "\"2025-07-10\"",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "now",
        category: "date",
        parameters: &[],
        returns: FelType::DateTime,
        return_description: None,
        description: "Returns the current date and time as an ISO 8601 dateTime string. Non-deterministic.",
        null_handling: Some("N/A — no parameters."),
        deterministic: false,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "now()",
            result_json: "\"2025-07-10T14:30:00.000Z\"",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "year",
        category: "date",
        parameters: &[Parameter {
            name: "date",
            fel_type: FelType::Date,
            description: Some("ISO 8601 date or dateTime string."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Extracts the 4-digit year from a date.",
        null_handling: Some("Null returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "year(@2025-07-10)",
                result_json: "2025",
                note: None,
            },
            Example {
                expression: "year($birthDate)",
                result_json: "1990",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "month",
        category: "date",
        parameters: &[Parameter {
            name: "date",
            fel_type: FelType::Date,
            description: Some("ISO 8601 date or dateTime string."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Extracts the month (1-12) from a date.",
        null_handling: Some("Null returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "month(@2025-07-10)",
            result_json: "7",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "day",
        category: "date",
        parameters: &[Parameter {
            name: "date",
            fel_type: FelType::Date,
            description: Some("ISO 8601 date or dateTime string."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Extracts the day of month (1-31) from a date.",
        null_handling: Some("Null returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "day(@2025-07-10)",
            result_json: "10",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "hours",
        category: "date",
        parameters: &[Parameter {
            name: "dateTime",
            fel_type: FelType::DateTime,
            description: Some("ISO 8601 dateTime or time string."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Extracts the hour component (0-23) from a dateTime or time value.",
        null_handling: Some("Null returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "hours(@2025-07-10T14:30:00Z)",
            result_json: "14",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "minutes",
        category: "date",
        parameters: &[Parameter {
            name: "dateTime",
            fel_type: FelType::DateTime,
            description: Some("ISO 8601 dateTime or time string."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Extracts the minute component (0-59) from a dateTime or time value.",
        null_handling: Some("Null returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "minutes(@2025-07-10T14:30:00Z)",
            result_json: "30",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "seconds",
        category: "date",
        parameters: &[Parameter {
            name: "dateTime",
            fel_type: FelType::DateTime,
            description: Some("ISO 8601 dateTime or time string."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Extracts the second component (0-59) from a dateTime or time value.",
        null_handling: Some("Null returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "seconds(@2025-07-10T14:30:45Z)",
            result_json: "45",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "time",
        category: "date",
        parameters: &[
            Parameter {
                name: "hours",
                fel_type: FelType::Number,
                description: Some("Hour (0-23)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "minutes",
                fel_type: FelType::Number,
                description: Some("Minute (0-59)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "seconds",
                fel_type: FelType::Number,
                description: Some("Second (0-59)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Time,
        return_description: None,
        description: "Constructs an HH:MM:SS time string from numeric components.",
        null_handling: Some("Null components treated as 0."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "time(14, 30, 0)",
                result_json: "\"14:30:00\"",
                note: None,
            },
            Example {
                expression: "time(9, 5, 30)",
                result_json: "\"09:05:30\"",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "dateDiff",
        category: "date",
        parameters: &[
            Parameter {
                name: "date1",
                fel_type: FelType::Date,
                description: Some("First date (ISO 8601)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "date2",
                fel_type: FelType::Date,
                description: Some("Second date (ISO 8601)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "unit",
                fel_type: FelType::String,
                description: Some("Unit of measurement."),
                required: true,
                variadic: false,
                allowed_values: Some(&["days", "months", "years"]),
            },
        ],
        returns: FelType::Number,
        return_description: None,
        description: "Returns the difference laterDate − earlierDate in the specified unit (arguments: date1 as laterDate, date2 as earlierDate). Result is positive when date1 > date2, negative when date1 < date2. For months/years, incomplete periods are truncated (not rounded).",
        null_handling: Some("Null or invalid dates return null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "dateDiff(@2025-07-10, @2025-01-01, 'days')",
                result_json: "190",
                note: None,
            },
            Example {
                expression: "dateDiff($endDate, $startDate, 'months')",
                result_json: "6",
                note: None,
            },
            Example {
                expression: "dateDiff(today(), $birthDate, 'years')",
                result_json: "35",
                note: Some("Age calculation"),
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "dateAdd",
        category: "date",
        parameters: &[
            Parameter {
                name: "date",
                fel_type: FelType::Date,
                description: Some("Base date (ISO 8601)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "amount",
                fel_type: FelType::Number,
                description: Some("Number of units to add (negative to subtract)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "unit",
                fel_type: FelType::String,
                description: Some("Unit of measurement."),
                required: true,
                variadic: false,
                allowed_values: Some(&["days", "months", "years"]),
            },
        ],
        returns: FelType::Date,
        return_description: Some("ISO 8601 date string (YYYY-MM-DD)."),
        description: "Adds the specified number of units to a date. Negative values subtract. Month/year arithmetic handles end-of-month overflow per the host language's Date implementation.",
        null_handling: Some("Null date returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "dateAdd(@2025-01-15, 30, 'days')",
                result_json: "\"2025-02-14\"",
                note: None,
            },
            Example {
                expression: "dateAdd(today(), 1, 'years')",
                result_json: "\"2026-07-10\"",
                note: None,
            },
            Example {
                expression: "dateAdd($startDate, -6, 'months')",
                result_json: "\"2025-01-10\"",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "timeDiff",
        category: "date",
        parameters: &[
            Parameter {
                name: "laterTime",
                fel_type: FelType::Time,
                description: Some("Later ISO 8601 time string (HH:MM:SS)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "earlierTime",
                fel_type: FelType::Time,
                description: Some("Earlier ISO 8601 time string (HH:MM:SS)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Number,
        return_description: Some(
            "Signed difference in whole seconds: laterTime minus earlierTime (positive when the first argument is later in the day).",
        ),
        description: "Difference in seconds between two time-of-day strings. Distinct from duration(), which parses an ISO 8601 duration and returns milliseconds.",
        null_handling: Some("Invalid time strings produce a diagnostic and null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "timeDiff('14:30:00', '13:00:00')",
                result_json: "5400",
                note: None,
            },
            Example {
                expression: "timeDiff('13:00:00', '14:30:00')",
                result_json: "-5400",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "duration",
        category: "date",
        parameters: &[Parameter {
            name: "isoDuration",
            fel_type: FelType::String,
            description: Some("ISO 8601 duration (PnYnMnDTnHnMnS subset), optional leading minus."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Parses a duration string and returns its length in milliseconds. Years/months in the date part use fixed 365-day years and 30-day months (not calendar arithmetic). Distinct from timeDiff, which compares two clock times in seconds.",
        null_handling: Some(
            "Null argument returns null. Invalid strings produce an error diagnostic and null.",
        ),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "duration('PT1H')",
                result_json: "3600000",
                note: None,
            },
            Example {
                expression: "duration('P1D')",
                result_json: "86400000",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
];
