//! Static builtin catalog data (`BUILTIN_FUNCTIONS`) and reserved names.
#![allow(clippy::missing_docs_in_private_items)]

use super::super::types::*;

pub(super) const ENTRIES: &[BuiltinFunctionCatalogEntry] = &[
    // ── money ─────────────────────────────────────────────────────────────────
    BuiltinFunctionCatalogEntry {
        name: "money",
        category: "money",
        parameters: &[
            Parameter {
                name: "amount",
                fel_type: FelType::Number,
                description: Some("Monetary amount."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "currency",
                fel_type: FelType::String,
                description: Some("ISO 4217 currency code (e.g., 'USD', 'EUR')."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Money,
        return_description: Some("Object: {amount: number, currency: string}."),
        description: "Constructs a money object from an amount and currency code.",
        null_handling: Some("Null arguments produce a money object with null/undefined fields."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "money(50000, 'USD')",
                result_json: "{\"amount\": 50000, \"currency\": \"USD\"}",
                note: None,
            },
            Example {
                expression: "money($total, 'EUR')",
                result_json: "{\"amount\": 12500, \"currency\": \"EUR\"}",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "moneyAmount",
        category: "money",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Money,
            description: Some("Money object."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Extracts the numeric amount from a money object.",
        null_handling: Some("Null or non-money value returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "moneyAmount($budget)",
            result_json: "50000",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "moneyCurrency",
        category: "money",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Money,
            description: Some("Money object."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::String,
        return_description: None,
        description: "Extracts the currency code from a money object.",
        null_handling: Some("Null or non-money value returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "moneyCurrency($budget)",
            result_json: "\"USD\"",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "moneyAdd",
        category: "money",
        parameters: &[
            Parameter {
                name: "a",
                fel_type: FelType::Money,
                description: Some("First money object."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "b",
                fel_type: FelType::Money,
                description: Some("Second money object. Must have the same currency as first."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Money,
        return_description: None,
        description: "Adds two money objects. Uses the currency from the first non-null operand. Per the spec, both operands SHOULD have the same currency; implementations MAY error on mismatched currencies.",
        null_handling: Some("Null operand returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "moneyAdd(money(100, 'USD'), money(250, 'USD'))",
            result_json: "{\"amount\": 350, \"currency\": \"USD\"}",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "moneySum",
        category: "money",
        parameters: &[Parameter {
            name: "values",
            fel_type: FelType::Array,
            description: Some("Array of money objects."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Money,
        return_description: None,
        description: "Sums an array of money objects. Returns a money object with the currency from the first element. All elements SHOULD have the same currency.",
        null_handling: Some("Null elements skipped. Empty array returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "moneySum($lineItems[*].cost)",
            result_json: "{\"amount\": 1500, \"currency\": \"USD\"}",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "moneySumWhere",
        category: "money",
        parameters: &[
            Parameter {
                name: "values",
                fel_type: FelType::Array,
                description: Some("Array of money objects."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "predicate",
                fel_type: FelType::Boolean,
                description: Some(
                    "FEL expression evaluated per element with '$' rebound to the current money value.",
                ),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Money,
        return_description: None,
        description: "Sums money array elements for which the predicate evaluates to true. Matched elements MUST share the same currency. The predicate is NOT pre-evaluated — it is evaluated once per element.",
        null_handling: Some("Null array returns null. No matches returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: true,
        examples: &[Example {
            expression: "moneySumWhere([money(100,'USD'), money(200,'USD')], moneyAmount($) > 50)",
            result_json: "{\"amount\": 300, \"currency\": \"USD\"}",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
];
