//! Static builtin catalog data (`BUILTIN_FUNCTIONS`) and reserved names.
#![allow(clippy::missing_docs_in_private_items)]

use super::super::types::*;

pub(super) const ENTRIES: &[BuiltinFunctionCatalogEntry] = &[
    // ── string ───────────────────────────────────────────────────────────────
    BuiltinFunctionCatalogEntry {
        name: "length",
        category: "string",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::String,
            description: Some("String to measure."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Returns the number of characters in the string.",
        null_handling: Some("Null returns 0."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "length('hello')",
                result_json: "5",
                note: None,
            },
            Example {
                expression: "length(null)",
                result_json: "0",
                note: None,
            },
            Example {
                expression: "length($name)",
                result_json: "12",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "contains",
        category: "string",
        parameters: &[
            Parameter {
                name: "haystack",
                fel_type: FelType::String,
                description: Some("String to search in."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "needle",
                fel_type: FelType::String,
                description: Some("Substring to find."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if the haystack string contains the needle substring. Case-sensitive.",
        null_handling: Some("Null haystack treated as empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "contains('hello world', 'world')",
                result_json: "true",
                note: None,
            },
            Example {
                expression: "contains($email, '@')",
                result_json: "true",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "startsWith",
        category: "string",
        parameters: &[
            Parameter {
                name: "value",
                fel_type: FelType::String,
                description: Some("String to test."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "prefix",
                fel_type: FelType::String,
                description: Some("Expected prefix."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if value starts with prefix. Case-sensitive.",
        null_handling: Some("Null value treated as empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "startsWith($url, 'https://')",
            result_json: "true",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "endsWith",
        category: "string",
        parameters: &[
            Parameter {
                name: "value",
                fel_type: FelType::String,
                description: Some("String to test."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "suffix",
                fel_type: FelType::String,
                description: Some("Expected suffix."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if value ends with suffix. Case-sensitive.",
        null_handling: Some("Null value treated as empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "endsWith($email, '.gov')",
            result_json: "true",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "substring",
        category: "string",
        parameters: &[
            Parameter {
                name: "value",
                fel_type: FelType::String,
                description: Some("Source string."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "start",
                fel_type: FelType::Number,
                description: Some("1-based start position."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "length",
                fel_type: FelType::Number,
                description: Some("Number of characters to extract."),
                required: false,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::String,
        return_description: None,
        description: "Extracts a substring starting at the 1-based position. If length is omitted, extracts to the end of the string.",
        null_handling: Some("Null value treated as empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "substring('abcdef', 2, 3)",
                result_json: "\"bcd\"",
                note: None,
            },
            Example {
                expression: "substring('abcdef', 4)",
                result_json: "\"def\"",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "replace",
        category: "string",
        parameters: &[
            Parameter {
                name: "value",
                fel_type: FelType::String,
                description: Some("Source string."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "search",
                fel_type: FelType::String,
                description: Some("Literal substring to find (NOT regex)."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "replacement",
                fel_type: FelType::String,
                description: Some("Replacement string."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::String,
        return_description: None,
        description: "Replaces ALL occurrences of the search literal with the replacement. Not regex — literal string match only.",
        null_handling: Some("Null value treated as empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "replace('hello world', 'world', 'there')",
                result_json: "\"hello there\"",
                note: None,
            },
            Example {
                expression: "replace($phone, '-', '')",
                result_json: "\"5551234567\"",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "upper",
        category: "string",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::String,
            description: Some("String to convert."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::String,
        return_description: None,
        description: "Converts string to uppercase.",
        null_handling: Some("Null treated as empty string, returns empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "upper('hello')",
            result_json: "\"HELLO\"",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "lower",
        category: "string",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::String,
            description: Some("String to convert."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::String,
        return_description: None,
        description: "Converts string to lowercase.",
        null_handling: Some("Null treated as empty string, returns empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "lower('HELLO')",
            result_json: "\"hello\"",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "trim",
        category: "string",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::String,
            description: Some("String to trim."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::String,
        return_description: None,
        description: "Removes leading and trailing whitespace.",
        null_handling: Some("Null treated as empty string, returns empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "trim('  hello  ')",
            result_json: "\"hello\"",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "matches",
        category: "string",
        parameters: &[
            Parameter {
                name: "value",
                fel_type: FelType::String,
                description: Some("String to test."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "pattern",
                fel_type: FelType::String,
                description: Some("Regular expression pattern."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
        ],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if the string matches the regular expression pattern. Pattern syntax follows the host language's regex engine (ECMA-262 for TypeScript, Python re for Python).",
        null_handling: Some("Null value treated as empty string."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "matches($ein, '^[0-9]{2}-[0-9]{7}$')",
                result_json: "true",
                note: None,
            },
            Example {
                expression: "matches($email, '^[^@]+@[^@]+$')",
                result_json: "true",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "format",
        category: "string",
        parameters: &[
            Parameter {
                name: "template",
                fel_type: FelType::String,
                description: Some("Format string with {0}, {1}, ... positional placeholders."),
                required: true,
                variadic: false,
                allowed_values: None,
            },
            Parameter {
                name: "args",
                fel_type: FelType::Any,
                description: Some("Values to substitute for placeholders."),
                required: true,
                variadic: true,
                allowed_values: None,
            },
        ],
        returns: FelType::String,
        return_description: None,
        description: "Positional string interpolation. Replaces {0}, {1}, etc. in the template with stringified arguments. Null arguments become empty string. Numbers strip trailing zeros. Booleans become 'true'/'false'.",
        null_handling: Some(
            "Null template returns empty string. Null arguments substituted as empty string.",
        ),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "format('{0} of {1}', $current, $total)",
                result_json: "\"3 of 10\"",
                note: None,
            },
            Example {
                expression: "format('Hello, {0}!', $name)",
                result_json: "\"Hello, Alice!\"",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
];
