//! Static builtin catalog data (`BUILTIN_FUNCTIONS`) and reserved names.
#![allow(clippy::missing_docs_in_private_items)]

use super::super::types::*;

pub(super) const ENTRIES: &[BuiltinFunctionCatalogEntry] = &[
    // ── type ─────────────────────────────────────────────────────────────────
    BuiltinFunctionCatalogEntry {
        name: "isNumber",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to test."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if the value is a finite number (not NaN).",
        null_handling: Some("Null returns false."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "isNumber(42)",
                result_json: "true",
                note: None,
            },
            Example {
                expression: "isNumber('42')",
                result_json: "false",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "isString",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to test."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if the value is a string.",
        null_handling: Some("Null returns false."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "isString('hello')",
                result_json: "true",
                note: None,
            },
            Example {
                expression: "isString(42)",
                result_json: "false",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "isDate",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to test."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if the value can be parsed as a valid date.",
        null_handling: Some("Null returns false."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "isDate('2025-07-10')",
                result_json: "true",
                note: None,
            },
            Example {
                expression: "isDate('not-a-date')",
                result_json: "false",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "isNull",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to test."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Boolean,
        return_description: None,
        description: "Returns true if the value is null, undefined, or empty string. Note: broader than a strict null check — empty string is also considered 'null' in FEL.",
        null_handling: Some("Null returns true (that's the point)."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "isNull(null)",
                result_json: "true",
                note: None,
            },
            Example {
                expression: "isNull('')",
                result_json: "true",
                note: None,
            },
            Example {
                expression: "isNull(0)",
                result_json: "false",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "typeOf",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to inspect."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::String,
        return_description: Some(
            "One of: 'string', 'number', 'boolean', 'array', 'object', 'null'.",
        ),
        description: "Returns the FEL type name of the value.",
        null_handling: Some("Null returns 'null'."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "typeOf(42)",
                result_json: "\"number\"",
                note: None,
            },
            Example {
                expression: "typeOf([1,2])",
                result_json: "\"array\"",
                note: None,
            },
            Example {
                expression: "typeOf(null)",
                result_json: "\"null\"",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    // cast functions: category changed cast → type to match schema (schema is authoritative)
    BuiltinFunctionCatalogEntry {
        name: "number",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to coerce to number."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Number,
        return_description: None,
        description: "Explicit type cast to number. Strings are parsed as numbers. Returns null if coercion fails.",
        null_handling: Some("Null returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "number('42')",
                result_json: "42",
                note: None,
            },
            Example {
                expression: "number('3.14')",
                result_json: "3.14",
                note: None,
            },
            Example {
                expression: "number('abc')",
                result_json: "null",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "string",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to coerce to string."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::String,
        return_description: None,
        description: "Explicit type cast to string. Null becomes empty string. Numbers, booleans, and dates are stringified.",
        null_handling: Some("Null returns empty string ''."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "string(42)",
                result_json: "\"42\"",
                note: None,
            },
            Example {
                expression: "string(true)",
                result_json: "\"true\"",
                note: None,
            },
            Example {
                expression: "string(null)",
                result_json: "\"\"",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "boolean",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to coerce to boolean."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Boolean,
        return_description: None,
        description: "Explicit type cast to boolean. Accepts: booleans (pass-through), numbers (0 = false, non-zero = true), strings 'true'/'false'. Other values produce an evaluation error.",
        null_handling: Some("Null returns false."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[
            Example {
                expression: "boolean(1)",
                result_json: "true",
                note: None,
            },
            Example {
                expression: "boolean(0)",
                result_json: "false",
                note: None,
            },
            Example {
                expression: "boolean('true')",
                result_json: "true",
                note: None,
            },
            Example {
                expression: "boolean(null)",
                result_json: "false",
                note: None,
            },
        ],
        since_version: "1.0",
        package: Package::Universal,
    },
    BuiltinFunctionCatalogEntry {
        name: "date",
        category: "type",
        parameters: &[Parameter {
            name: "value",
            fel_type: FelType::Any,
            description: Some("Value to validate/coerce as ISO 8601 date."),
            required: true,
            variadic: false,
            allowed_values: None,
        }],
        returns: FelType::Date,
        return_description: None,
        description: "Validates and returns the input as an ISO 8601 date string. If the input is not a valid date, produces an evaluation error.",
        null_handling: Some("Null returns null."),
        deterministic: true,
        emit_deterministic_explicitly: false,
        short_circuit: false,
        examples: &[Example {
            expression: "date('2025-07-10')",
            result_json: "\"2025-07-10\"",
            note: None,
        }],
        since_version: "1.0",
        package: Package::Universal,
    },
];
